package:
  name: ros-humble-webots-ros2-driver
  version: 2023.1.1
source:
  git_url: https://github.com/ros2-gbp/webots_ros2-release.git
  git_rev: release/humble/webots_ros2_driver/2023.1.1-2
  folder: ros-humble-webots-ros2-driver/src/work
  patches:
    - patch/ros-humble-webots-ros2-driver.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-python
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-geometry-msgs
    - ros-humble-pluginlib
    - ros-humble-python-cmake-module
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tinyxml2-vendor
    - ros-humble-vision-msgs
    - ros-humble-webots-ros2-importer
    - ros-humble-webots-ros2-msgs
    - ros2-distro-mutex 0.5 humble
    - yaml-cpp
  run:
    - python
    - ros-humble-geometry-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tinyxml2-vendor
    - ros-humble-vision-msgs
    - ros-humble-webots-ros2-importer
    - ros-humble-webots-ros2-msgs
    - ros2-distro-mutex 0.5 humble
    - yaml-cpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
