package:
  name: ros-humble-rmw-cyclonedds-cpp
  version: 1.3.4
source:
  git_url: https://github.com/ros2-gbp/rmw_cyclonedds-release.git
  git_rev: release/humble/rmw_cyclonedds_cpp/1.3.4-1
  folder: ros-humble-rmw-cyclonedds-cpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
    - sel(build_platform != target_platform): ros-humble-cyclonedds
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-cyclonedds
    - ros-humble-iceoryx-binding-c
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-rmw
    - ros-humble-rmw-dds-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros-humble-tracetools
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-cyclonedds
    - ros-humble-iceoryx-binding-c
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-rmw
    - ros-humble-rmw-dds-common
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros-humble-tracetools
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
