package:
  name: ros-humble-cv-bridge
  version: 3.2.1
source:
  git_url: https://github.com/ros2-gbp/vision_opencv-release.git
  git_rev: release/humble/cv_bridge/3.2.1-1
  folder: ros-humble-cv-bridge/src/work
  patches:
    - patch/ros-humble-cv-bridge.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - boost
    - boost-cpp
    - libopencv
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - py-opencv
    - python
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-python-cmake-module
    - ros-humble-rcpputils
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - boost
    - libopencv
    - numpy
    - py-opencv
    - python
    - ros-humble-ament-index-python
    - ros-humble-rcpputils
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
