package:
  name: ros-humble-robot-controllers
  version: 0.9.3
source:
  git_url: https://github.com/fetchrobotics-gbp/robot_controllers-ros2-release.git
  git_rev: release/humble/robot_controllers/0.9.3-1
  folder: ros-humble-robot-controllers/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - orocos-kdl
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gtest
    - ros-humble-angles
    - ros-humble-control-msgs
    - ros-humble-geometry-msgs
    - ros-humble-kdl-parser
    - ros-humble-nav-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-action
    - ros-humble-robot-controllers-interface
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-trajectory-msgs
    - ros-humble-urdf
    - ros2-distro-mutex 0.5 humble
  run:
    - orocos-kdl
    - python
    - ros-humble-angles
    - ros-humble-control-msgs
    - ros-humble-geometry-msgs
    - ros-humble-kdl-parser
    - ros-humble-nav-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-action
    - ros-humble-robot-controllers-interface
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-trajectory-msgs
    - ros-humble-urdf
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
