package:
  name: ros-humble-rviz-common
  version: 11.2.10
source:
  git_url: https://github.com/ros2-gbp/rviz-release.git
  git_rev: release/humble/rviz_common/11.2.10-1
  folder: ros-humble-rviz-common/src/work
  patches:
    - patch/ros-humble-rviz-common.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - qt-main
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gmock
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-ament-cmake-xmllint
    - ros-humble-ament-lint-auto
    - ros-humble-geometry-msgs
    - ros-humble-message-filters
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rcpputils
    - ros-humble-resource-retriever
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tinyxml2-vendor
    - ros-humble-urdf
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.5 humble
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - qt-main
    - ros-humble-geometry-msgs
    - ros-humble-message-filters
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rcpputils
    - ros-humble-resource-retriever
    - ros-humble-ros-workspace
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tinyxml2-vendor
    - ros-humble-urdf
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
