package:
  name: ros-humble-ur-description
  version: 2.1.3
source:
  git_url: https://github.com/ros2-gbp/ur_description-release.git
  git_rev: release/humble/ur_description/2.1.3-1
  folder: ros-humble-ur-description/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-pytest
    - ros-humble-launch-testing-ament-cmake
    - ros-humble-launch-testing-ros
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-xacro
    - ros2-distro-mutex 0.5 humble
    - urdfdom
  run:
    - python
    - ros-humble-joint-state-publisher-gui
    - ros-humble-launch
    - ros-humble-launch-ros
    - ros-humble-robot-state-publisher
    - ros-humble-ros-workspace
    - ros-humble-rviz2
    - ros-humble-urdf
    - ros-humble-xacro
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
