package:
  name: ros-humble-ntrip-client-node
  version: 0.5.2
source:
  git_url: https://github.com/ros2-gbp/ublox_dgnss-release.git
  git_rev: release/humble/ntrip_client_node/0.5.2-1
  folder: ros-humble-ntrip-client-node/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-copyright
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-libcurl-vendor
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rtcm-msgs
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-libcurl-vendor
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-workspace
    - ros-humble-rtcm-msgs
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
