package:
  name: ros-humble-nav2-costmap-2d
  version: 1.1.13
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/humble/nav2_costmap_2d/1.1.13-1
  folder: ros-humble-nav2-costmap-2d/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-angles
    - ros-humble-geometry-msgs
    - ros-humble-laser-geometry
    - ros-humble-launch
    - ros-humble-launch-testing
    - ros-humble-map-msgs
    - ros-humble-message-filters
    - ros-humble-nav-msgs
    - ros-humble-nav2-common
    - ros-humble-nav2-lifecycle-manager
    - ros-humble-nav2-map-server
    - ros-humble-nav2-msgs
    - ros-humble-nav2-util
    - ros-humble-nav2-voxel-grid
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tf2-sensor-msgs
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-angles
    - ros-humble-geometry-msgs
    - ros-humble-laser-geometry
    - ros-humble-map-msgs
    - ros-humble-message-filters
    - ros-humble-nav-msgs
    - ros-humble-nav2-msgs
    - ros-humble-nav2-util
    - ros-humble-nav2-voxel-grid
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-tf2-sensor-msgs
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
