package:
  name: ros-humble-visp
  version: 3.5.0
source:
  git_url: https://github.com/ros2-gbp/visp-release.git
  git_rev: release/humble/visp/3.5.0-2
  folder: ros-humble-visp/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
    - sel(build_platform != target_platform): doxygen
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - bzip2
    - eigen
    - graphviz
    - libjpeg-turbo
    - liblapack
    - libopencv
    - libpng
    - libxml2
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - py-opencv
    - python
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
    - xorg-libx11
    - sel(build_platform == target_platform): doxygen
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - eigen
    - libjpeg-turbo
    - liblapack
    - libopencv
    - libpng
    - libxml2
    - py-opencv
    - python
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
    - xorg-libx11
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
