package:
  name: ros-humble-realsense2-camera
  version: 4.54.1
source:
  git_url: https://github.com/IntelRealSense/realsense-ros-release.git
  git_rev: release/humble/realsense2_camera/4.54.1-1
  folder: ros-humble-realsense2-camera/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - eigen
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-builtin-interfaces
    - ros-humble-cv-bridge
    - ros-humble-diagnostic-updater
    - ros-humble-geometry-msgs
    - ros-humble-image-transport
    - ros-humble-librealsense2
    - ros-humble-nav-msgs
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-realsense2-camera-msgs
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
  run:
    - eigen
    - python
    - ros-humble-builtin-interfaces
    - ros-humble-cv-bridge
    - ros-humble-diagnostic-updater
    - ros-humble-geometry-msgs
    - ros-humble-image-transport
    - ros-humble-launch-ros
    - ros-humble-librealsense2
    - ros-humble-nav-msgs
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-realsense2-camera-msgs
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
