package:
  name: ros-humble-nav2-bringup
  version: 1.1.13
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/humble/nav2_bringup/1.1.13-1
  folder: ros-humble-nav2-bringup/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-launch
    - ros-humble-launch-ros
    - ros-humble-launch-testing
    - ros-humble-nav2-common
    - ros-humble-navigation2
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-launch-ros
    - ros-humble-nav2-common
    - ros-humble-navigation2
    - ros-humble-ros-workspace
    - ros-humble-slam-toolbox
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
