package:
  name: ros-humble-ros2-control
  version: 2.38.0
source:
  git_url: https://github.com/ros2-gbp/ros2_control-release.git
  git_rev: release/humble/ros2_control/2.38.0-1
  folder: ros-humble-ros2-control/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-controller-interface
    - ros-humble-controller-manager
    - ros-humble-controller-manager-msgs
    - ros-humble-hardware-interface
    - ros-humble-joint-limits
    - ros-humble-ros-workspace
    - ros-humble-ros2-control-test-assets
    - ros-humble-ros2controlcli
    - ros-humble-transmission-interface
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
