package:
  name: ros-humble-apriltag-ros
  version: 3.1.2
source:
  git_url: https://github.com/ros2-gbp/apriltag_ros-release.git
  git_rev: release/humble/apriltag_ros/3.1.2-1
  folder: ros-humble-apriltag-ros/src/work
  patches:
    - patch/ros-humble-apriltag-ros.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - eigen
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-clang-format
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-lint-auto
    - ros-humble-apriltag
    - ros-humble-apriltag-msgs
    - ros-humble-cv-bridge
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-apriltag
    - ros-humble-apriltag-msgs
    - ros-humble-cv-bridge
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
