package:
  name: ros-humble-moveit-ros-occupancy-map-monitor
  version: 2.5.5
source:
  git_url: https://github.com/ros2-gbp/moveit2-release.git
  git_rev: release/humble/moveit_ros_occupancy_map_monitor/2.5.5-1
  folder: ros-humble-moveit-ros-occupancy-map-monitor/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - eigen
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gmock
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-eigen3-cmake-module
    - ros-humble-geometric-shapes
    - ros-humble-moveit-common
    - ros-humble-moveit-core
    - ros-humble-moveit-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
  run:
    - eigen
    - python
    - ros-humble-eigen3-cmake-module
    - ros-humble-geometric-shapes
    - ros-humble-moveit-common
    - ros-humble-moveit-core
    - ros-humble-moveit-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-ros-workspace
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
