package:
  name: ros-humble-tf2
  version: 0.25.5
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/humble/tf2/0.25.5-1
  folder: ros-humble-tf2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - console_bridge
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-copyright
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-ament-cmake-xmllint
    - ros-humble-builtin-interfaces
    - ros-humble-console-bridge-vendor
    - ros-humble-geometry-msgs
    - ros-humble-rcutils
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-cpp
    - ros2-distro-mutex 0.5 humble
  run:
    - console_bridge
    - python
    - ros-humble-builtin-interfaces
    - ros-humble-console-bridge-vendor
    - ros-humble-geometry-msgs
    - ros-humble-rcutils
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-cpp
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
