package:
  name: ros-humble-cartographer-ros
  version: 2.0.9000
source:
  git_url: https://github.com/ros2-gbp/cartographer_ros-release.git
  git_rev: release/humble/cartographer_ros/2.0.9000-2
  folder: ros-humble-cartographer-ros/src/work
  patches:
    - patch/ros-humble-cartographer-ros.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - cartographer
    - cartographer 2.*
    - eigen
    - gflags
    - glog
    - gmock
    - libabseil
    - libboost-devel
    - numpy
    - pcl
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-builtin-interfaces
    - ros-humble-cartographer-ros-msgs
    - ros-humble-geometry-msgs
    - ros-humble-nav-msgs
    - ros-humble-pcl-conversions
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosbag2-cpp
    - ros-humble-rosbag2-storage
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-eigen
    - ros-humble-tf2-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.5 humble
    - sphinx
  run:
    - cartographer
    - eigen
    - gflags
    - glog
    - libabseil
    - pcl
    - python
    - ros-humble-builtin-interfaces
    - ros-humble-cartographer-ros-msgs
    - ros-humble-geometry-msgs
    - ros-humble-launch
    - ros-humble-nav-msgs
    - ros-humble-pcl-conversions
    - ros-humble-rclcpp
    - ros-humble-robot-state-publisher
    - ros-humble-ros-workspace
    - ros-humble-rosbag2-cpp
    - ros-humble-rosbag2-storage
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2
    - ros-humble-tf2-eigen
    - ros-humble-tf2-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
