package:
  name: ros-humble-ros2run
  version: 0.18.8
source:
  git_url: https://github.com/ros2-gbp/ros2cli-release.git
  git_rev: release/humble/ros2run/0.18.8-1
  folder: ros-humble-ros2run/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - pytest
    - pytest-timeout
    - python
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-pep257
    - ros-humble-ament-xmllint
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros2-distro-mutex 0.5 humble
    - setuptools
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros-humble-ros2pkg
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
