package:
  name: ros-humble-robot-localization
  version: 3.5.2
source:
  git_url: https://github.com/ros2-gbp/robot_localization-release.git
  git_rev: release/humble/robot_localization/3.5.2-1
  folder: ros-humble-robot-localization/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - boost-cpp
    - eigen
    - geographiclib-cpp
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-angles
    - ros-humble-builtin-interfaces
    - ros-humble-diagnostic-msgs
    - ros-humble-diagnostic-updater
    - ros-humble-geographic-msgs
    - ros-humble-geometry-msgs
    - ros-humble-launch-ros
    - ros-humble-launch-testing-ament-cmake
    - ros-humble-message-filters
    - ros-humble-nav-msgs
    - ros-humble-rclcpp
    - ros-humble-rmw-implementation
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-eigen
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.5 humble
  run:
    - boost-cpp
    - eigen
    - geographiclib-cpp
    - python
    - ros-humble-angles
    - ros-humble-diagnostic-msgs
    - ros-humble-diagnostic-updater
    - ros-humble-geographic-msgs
    - ros-humble-geometry-msgs
    - ros-humble-message-filters
    - ros-humble-nav-msgs
    - ros-humble-rclcpp
    - ros-humble-rmw-implementation
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-eigen
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
