package:
  name: ros-humble-generate-parameter-library
  version: 0.3.7
source:
  git_url: https://github.com/ros2-gbp/generate_parameter_library-release.git
  git_rev: release/humble/generate_parameter_library/0.3.7-1
  folder: ros-humble-generate-parameter-library/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - fmt
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-python
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-generate-parameter-library-py
    - ros-humble-parameter-traits
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rsl
    - ros-humble-tcb-span
    - ros-humble-tl-expected
    - ros2-distro-mutex 0.5 humble
  run:
    - fmt
    - python
    - ros-humble-generate-parameter-library-py
    - ros-humble-parameter-traits
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-rsl
    - ros-humble-tcb-span
    - ros-humble-tl-expected
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
