package:
  name: ros-humble-joy-teleop
  version: 1.5.0
source:
  git_url: https://github.com/ros2-gbp/teleop_tools-release.git
  git_rev: release/humble/joy_teleop/1.5.0-1
  folder: ros-humble-joy-teleop/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-action-tutorials-interfaces
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-pep257
    - ros-humble-ament-xmllint
    - ros-humble-example-interfaces
    - ros-humble-geometry-msgs
    - ros-humble-launch-ros
    - ros-humble-launch-testing
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-test-msgs
    - ros2-distro-mutex 0.5 humble
    - setuptools
  run:
    - python
    - ros-humble-control-msgs
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-py
    - ros-humble-sensor-msgs
    - ros-humble-teleop-tools-msgs
    - ros-humble-trajectory-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
